export const LIST = 'PSLIST';

export const IMMO = 'IMMOBILER';
export const BROADCAST = 'PSBROADCAST';
export const APE = 'PSAPE';

export const AUTOCALL_BODY_FULL_TEMPLATE = "AUTOCALL_BODY_FULL_TEMPLATE";
export const AUTOCALL_FULL_TEMPLATE = "AUTOCALL_FULL_TEMPLATE";
export const AUTOCALL_SHORT_TEMPLATE = "AUTOCALL_SHORT_TEMPLATE";
export const AUTOCALL_MEDIUM_TEMPLATE = "AUTOCALL_MEDIUM_TEMPLATE";

