export const PSLIST = 'PSLIST'; //juste un produit structure
export const IMMO = 'IMMOBILER';

export const TICKET = "TICKET";
export const PSBROADCAST = 'PSBROADCAST';
export const PSSRPLIST = "PSSRPLIST";
export const PSAPE = 'PSAPE';
export const PSPP = 'PSPP';

//specific template for autocall template
export const BROADCAST_PS_FULL_TEMPLATE = "BROADCAST_PS_FULL_TEMPLATE";

//specific template for ticket template
export const TICKET_MEDIUM_TEMPLATE = "TICKET_MEDIUM_TEMPLATE";
export const TICKET_FULL_TEMPLATE = "TICKET_FULL_TEMPLATE";

//specific template for autocall template
export const AUTOCALL_BODY_FULL_TEMPLATE = "AUTOCALL_BODY_FULL_TEMPLATE";
export const AUTOCALL_FULL_TEMPLATE = "AUTOCALL_FULL_TEMPLATE";
export const AUTOCALL_HEADER_FULL_TEMPLATE = "AUTOCALL_HEADER_FULL_TEMPLATE";
export const AUTOCALL_HEADER_MEDIUM_TEMPLATE = "AUTOCALL_HEADER_MEDIUM_TEMPLATE";
export const AUTOCALL_DETAIL_FULL_TEMPLATE = "AUTOCALL_DETAIL_FULL_TEMPLATE";
export const AUTOCALL_TICKET_TEMPLATE = "AUTOCALL_TICKET_TEMPLATE";
export const AUTOCALL_SHORT_TEMPLATE = "AUTOCALL_SHORT_TEMPLATE";
export const AUTOCALL_MEDIUM_TEMPLATE = "AUTOCALL_MEDIUM_TEMPLATE";



