export const STURCTUREDPRODUCT_CREATION = 'STURCTURED PRODUCT CREATION';
export const STURCTUREDPRODUCT_STATE = 'STURCTURED PRODUCT STATE';
export const IMMO = 'IMMOBILER';
export const BROADCAST = 'BROADCAST';

